account!na_required_for_network_service: 0x01
account.daemon!background_awaking_periodicity: 0x00002a30
account.daemon!schedule_periodicity: 0x00000e10
account.daemon!profile_sync_interval: 0x00004650
account.daemon!na_info_refresh_interval: 0x0000b6d0
am.display!transition_layer_enabled: 0x01
am.gpu!gpu_scheduling_enabled: 0x01
am.gpu!gpu_scheduling_frame_time_us: 0x0001c7ba
am.gpu!gpu_scheduling_fg_app_us: 0x0001c5c6
am.gpu!gpu_scheduling_bg_app_us: 0x00019834
am.gpu!gpu_scheduling_oa_us: 0x000001f4
am.gpu!gpu_scheduling_fg_sa_us: 0x00002d92
am.gpu!gpu_scheduling_bg_sa_us: 0x00000000
am.gpu!gpu_scheduling_fg_la_us: 0x00002d92
am.gpu!gpu_scheduling_partial_fg_la_us: 0x000007d0
am.gpu!gpu_scheduling_bg_la_us: 0x00000000
audio!audren_log_enabled: 0x00
audio!audout_log_enabled: 0x00
audio!audin_log_enabled: 0x00
audio!hwopus_log_enabled: 0x00
audio!adsp_log_enabled: 0x00
audio!suspend_for_debugger_enabled: 0x00
bgtc!enable_battery_saver: 0x00000001
bgtc!leaving_halfawake_margin: 0x00000003
bgtc!battery_threshold_save: 0x0000001e
bgtc!battery_threshold_stop: 0x0000000f
bgtc!minimum_interval_normal: 0x00000708
bgtc!minimum_interval_save: 0x00015180
boot!force_maintenance: 0x00
capsrv!screenshot_layerstack: 'screenshot'
capsrv!enable_album_screenshot_filedata_verification: 0x01
devmenu!enable_application_update: 0x01
devmenu!enable_exhibition_mode: 0x00
eclct!analytics_override: 0x00
eclct!analytics_pollperiod: 0x00015180
err!applet_auto_close: 0x00
friends!background_processing: 0x01
gpu_core_dump!auto_dump: 0x00
htc!disconnection_emulation: 0x00
idle!dim_level_percent_lcd: 0x0000000a
idle!dim_level_percent_tv: 0x00000046
lm!enable_sd_card_logging: 0x00
lm!sd_card_log_output_directory: 'NxBinLogs'
mii!is_db_test_mode_enabled: 0x00
news!system_version: 0x00000001
nfp!not_locked_tag: 0x01
nfp!play_report: 0x00
nifm!is_communication_control_enabled_for_test: 0x00
nim.install!prefer_delta_evenif_inefficient: 0x00
ns.notification!retry_interval: 0x0000003c
ns.notification!enable_network_update: 0x01
ns.notification!enable_download_task_list: 0x01
ns.notification!enable_version_list: 0x01
ns.sdcard!mount_sdcard: 0x01
omm!operation_mode_policy: 'auto'
omm!sleep_fade_in_ms: 0x00000032
omm!sleep_fade_out_ms: 0x00000064
omm!charging_sign_ms: 0x00000bb8
omm!low_battery_sign_ms: 0x00000bb8
omm!sign_fade_in_ms: 0x00000000
omm!sign_fade_out_ms: 0x00000190
omm!sign_wait_layer_visible_ms: 0x00000064
omm!startup_fade_in_ms: 0x000000c8
omm!startup_fade_out_ms: 0x00000190
omm!backlight_off_ms_on_handheld_switch: 0x00000096
pcm!enable: 0x01
pctl!intermittent_task_interval_seconds: 0x00005460
prepo!devmenu_prepo_page_view: 0x00
prepo!background_processing: 0x01
snap_shot_dump!auto_dump: 0x00
snap_shot_dump!output_dir: '%USERPROFILE%/Documents/Nintendo/NXDMP'
snap_shot_dump!full_dump: 0x00
systemconfig!field_testing: 0x00
systemconfig!exhivision: 0x00
systempowerstate!always_reboot: 0x00
systempowerstate!power_state_message_emulation_trigger_time: 0x00000000
systempowerstate!power_state_message_to_emulate: 0x00000000
target_manager!device_name: ''
time!standard_steady_clock_test_offset_minutes: 0x00000000
vulnerability!needs_update_vulnerability_policy: 0x00000000
apm!performance_mode_policy: 'auto'
apm!sdev_throttling_enabled: 0x01
apm!sdev_throttling_additional_delay_us: 0x00003e80
apm!battery_draining_enabled: 0x00
bcat!production_mode: 0x01
bpc!enable_quasi_off: 0x01
bsp0!usb: 'UDS'
bsp0!tm_transport: 'USB'
bluetooth_debug!skip_boot: 0x00
fatal!transition_to_fatal: 0x01
hid_debug!enables_debugpad: 0x00
hid_debug!manages_devices: 0x01
npns!background_processing: 0x01
npns!logmanager_redirection: 0x01
npns!sleep_processing_timeout: 0x0000001e
npns!sleep_periodic_interval: 0x00002a30
ns.applet!overlay_applet_id: '0x010000000000100c'
ns.applet!system_applet_id: '0x0100000000001000'
nsd!environment_identifier: 'lp1'
nsd!test_mode: 0x00
ntc!is_autonomic_correction_enabled: 0x01
ntc!autonomic_correction_interval_seconds: 0x000d2f00
ntc!autonomic_correction_failed_retry_interval_seconds: 0x00000e10
ntc!autonomic_correction_immediate_try_count_max: 0x00000004
ntc!autonomic_correction_immediate_try_interval_milliseconds: 0x00001388
pdm!save_playlog: 0x01
productinfo!product_name: 'Nintendo Switch'
productinfo!cec_osd_name: 'NintendoSwitch'
systemreport!enabled: 0x01
systemsleep!enter_sleep: 0x01
systemsleep!enter_sc7: 0x01
systemsleep!keep_vdd_core: 0x01
systemsleep!disable_tma_sleep: 0x00
systemsleep!disable_auto_sleep: 0x00
systemsleep!override_auto_sleep_time: 0x00000000
systemsleep!sleep_pending_time_ms: 0x00003a98
systemsleep!hush_time_after_brief_power_button_press_ms: 0x000003e8
systemsleep!transition_timeout_sec: 0x0000003c
systemsleep!dummy_event_auto_wake: 0x00
systemupdate!debug_id: '0x0000000000000000'
systemupdate!debug_version: 0x00000000
systemupdate!enable_network_service: 0x01
systemupdate!bgnup_retry_seconds: 0x0000003c
systemupdate!enable_background_download_stress_testing: 0x00
tc!iir_filter_gain_soc: 0x00000064
tc!iir_filter_gain_pcb: 0x00000064
tc!tskin_soc_coefficients_handheld: '[5464, 174190]'
tc!tskin_soc_coefficients_console: '[6182, 112480]'
tc!tskin_pcb_coefficients_handheld: '[5464, 174190]'
tc!tskin_pcb_coefficients_console: '[6182, 112480]'
tc!tskin_select: 'both'
tc!tskin_rate_table_handheld: '[[-1000000, 40000, 0, 0], [36000, 43000, 51, 51], [43000, 48000, 51, 102], [48000, 53000, 102, 153], [53000, 1000000, 153, 153], [48000, 1000000, 153, 153]]'
tc!tskin_rate_table_console: '[[-1000000, 43000, 51, 51], [43000, 53000, 51, 153], [53000, 58000, 153, 255], [58000, 1000000, 255, 255]]'
tc!rate_select: 'both'
tc!log_enabled: 0x00
tc!sleep_enabled: 0x01
wlan_debug!skip_wlan_boot: 0x00